## **Data Acquisition and Exploration**

This notebook demonstrates the acquisition of datasets in CSV, XLSX, and JSON formats. The datasets are loaded using pandas into separate DataFrames, and the first 10 rows of each dataset are displayed.

In [5]:
import pandas as pd

In [8]:
df1 = pd.read_csv("/content/Mydata/county-delinquencies-v2.csv")
df1.head(10)

,FIPS,County,State,"Credit Card Delinquency Rate, 2024","Percent Change in Credit Card Delinquency Rate, 2022 to 2024","Number of Residents with a Credit Card Delinquency, 2024"
0,1001,"Autauga County, Alabama",Alabama,5.7,17.400000,1376
1,1003,"Baldwin County, Alabama",Alabama,5.4,44.299999,6005
2,1005,"Barbour County, Alabama",Alabama,9.7,45.099998,810
3,1007,"Bibb County, Alabama",Alabama,7.1,1.700000,562
4,1009,"Blount County, Alabama",Alabama,8.5,41.700001,1912
5,1011,"Bullock County, Alabama",Alabama,10.2,14.400000,366
6,1013,"Butler County, Alabama",Alabama,10.3,30.700001,618
7,1015,"Calhoun County, Alabama",Alabama,7.7,29.500000,3214
8,1017,"Chambers County, Alabama",Alabama,8.5,40.299999,1030
9,1019,"Cherokee County, Alabama",Alabama,5.5,12.400000,486

### **Dataset 1: County Credit Card Delinquency**

This dataset provides county-level information about credit card delinquency rates in 2024 and changes in rates from 2022 to 2024. It also includes the estimated number of county residents with credit card delinquencies in 2024.

**Features**

**FIPS:**
Geographic codes used to identify each county

**County:**
The names of each county used in the dataset

**State:**
The state where each county is located

**Credit Card Delinquency Rate, 2024:**
The percentage of credit cards that were delinquent in 2024

**Percent Change in Credit Card Delinquency Rate, 2022 to 2024:**
The percentage change in the county's credit card delinquency rate between the years 2022 and 2024  

**Number of Residents with a Credit Card Delinquency, 2024:**
The estimated number of residents in the county with credit card delinquency in 2024

In [6]:
df2 = pd.read_csv("/content/Mydata/gasprices_combined.csv")
df2.head(10)

,state_name,state_abbr,state_code,stcd,cd_code,date,gasprices_nominal,gasprices_real
0,Alabama,AL,1,NaN,NaN,2024-08-21,3.01,3.08
1,Alaska,AK,2,NaN,NaN,2024-08-21,3.26,3.34
2,Arizona,AZ,4,NaN,NaN,2024-08-21,3.42,3.50
3,Arkansas,AR,5,NaN,NaN,2024-08-21,2.80,2.86
4,California,CA,6,NaN,NaN,2024-08-21,4.59,4.69
5,Colorado,CO,8,NaN,NaN,2024-08-21,3.23,3.31
6,Connecticut,CT,9,NaN,NaN,2024-08-21,3.46,3.54
7,Delaware,DE,10,NaN,NaN,2024-08-21,3.23,3.31
8,District of Columbia,DC,11,NaN,NaN,2024-08-21,3.70,3.78
9,Florida,FL,12,NaN,NaN,2024-08-21,3.46,3.54

## **Dataset 2 Gas Prices Combined**

This dataset provides state-level information on the real and nominal gas prices between the years 2024 and 2026. It includes geographic information for each state along with nominal and inflation adjusted gas prices recorded at specific dates.

**Features**

**State_name:** The name of the state where the gas price data was collected

**State_abbr:**
Two-letter abbreviation used to identify the state

**State_code:**
Numerical code assigned to each state

**stcd:**
Geographic code used to identify each state

**cd_code:**
Geographic code used to identify the congressional district

**date:**
Calendar date  when the price was recorded

**gasprices_nominal:**
Gas prices based on the wholesale value at the time of data collection

**gasprices_real:**
The gas price adjusted for inflation, to allow for comparison across different time periods

In [9]:
df3 = pd.read_excel("/content/Mydata/Funding Free Community College_Data.xlsx", header=1)
df3.head(10)

,State1,Average Tuition and Fees,Federal Payment,20% State Payment,Additional State Payment,Total State Cost,Excess Funding
0,New Hampshire,7336.63,3302.4,825.6,3208.63,4034.23,0.0
1,Vermont,6414.00,3302.4,825.6,2286.00,3111.60,0.0
2,South Dakota,6026.02,3302.4,825.6,1898.02,2723.62,0.0
3,Minnesota,5381.05,3302.4,825.6,1253.05,2078.65,0.0
4,New York,5229.22,3302.4,825.6,1101.22,1926.82,0.0
5,Pennsylvania,5173.49,3302.4,825.6,1045.49,1871.09,0.0
6,Virginia,5118.32,3302.4,825.6,990.32,1815.92,0.0
7,Massachusetts,4991.39,3302.4,825.6,863.39,1688.99,0.0
8,Iowa,4922.82,3302.4,825.6,794.82,1620.42,0.0
9,North Dakota,4700.05,3302.4,825.6,572.05,1397.65,0.0

## **Dataset 3: Community College**

The dataset provides information on estimated tuition and funding cost associated with providing free community college. It includes tuition and fees, federal and state payments, total state costs, and excess funding.

**Features**

**State1:** Name of the state represented in the dataset

**Average Tuition and Fees:** Average amount students would pay for tuition and fees at community college

**Federal Payment:** Amount of funding provided through federal financial support

**20% State Payment:** The estimated amount the state would contribute based on 20% of tuition and fees

**Additional State Payment:** The additional funding that would be provided by the state

**Total State Cost:** Total estimated cost to the state after accounting for applicable payment and funding

**Excess Funding:** Amount of funding leftover after estimated costs are covered

In [10]:
df4 = pd.read_excel("/content/Mydata/health-workforce-education-data-assignedsexatbirth.xlsx")
df4.head(10)

,LicenseName,Region,WorkforceCategory,InitialEduLevel,InitialEduLevelRWT,HighestEduLevel,HighestEduLevelRWT,SexAtBirth
0,Advanced Practice Pharmacist,Central Coast,Allied Health,Doctoral Degree,4.315152,Doctoral Degree,4.327273,Female
1,Advanced Practice Pharmacist,Greater Bay Area,Allied Health,Bachelor's Degree,2.092195,Bachelor's Degree,2.098072,Male
2,Advanced Practice Pharmacist,Greater Bay Area,Allied Health,Bachelor's Degree,1.673222,Doctoral Degree,1.727273,Female
3,Advanced Practice Pharmacist,Greater Bay Area,Allied Health,Doctoral Degree,35.544426,Doctoral Degree,35.770937,Female
4,Advanced Practice Pharmacist,Greater Bay Area,Allied Health,Doctoral Degree,14.647164,Doctoral Degree,14.518871,Male
5,Advanced Practice Pharmacist,Inland Empire,Allied Health,Bachelor's Degree,1.643867,Bachelor's Degree,1.648485,Male
6,Advanced Practice Pharmacist,Inland Empire,Allied Health,Doctoral Degree,14.452333,Doctoral Degree,14.492929,Female
7,Advanced Practice Pharmacist,Inland Empire,Allied Health,Doctoral Degree,8.870034,Doctoral Degree,8.894949,Male
8,Advanced Practice Pharmacist,Los Angeles County,Allied Health,Bachelor's Degree,0.804810,Bachelor's Degree,0.807071,Female
9,Advanced Practice Pharmacist,Los Angeles County,Allied Health,Bachelor's Degree,0.943939,Bachelor's Degree,0.946591,Male

## **Dataset 4: Health Workforce Education by Assigned Sex at Birth**

This dataset contains information about the education and characteristics of health workforce professionals across different occupations and geographic regions. It includes their education levels, professional categories, and sex assigned at birth.

**Features**

**LicenseName:** Name of the professional license associated with profession

**Region:** Geographic location where the health workforce data was reported

**WorkforceCategory:** Specific classification of healthcare profession

**InitialEduLevel:** Educational level of health professional when they first entered the workforce

**InitialEduLevelRWT:** A measurement value associated with the professional's initial education level

**HighestEduLevel:** The highest level of education achieved by the health professional

**HighestEduLevelRWT:** A measurement value associated with the professional's highest education level

**SexAtBirth:** The sex the professional was assigned at birth

In [11]:
df5 = pd.read_excel("/content/Mydata/2024-health-workforce-language-age-data.xlsx")
df5.head(10)

,WorkforceCategory,LicenseName,Region,AgeRange,AsianandPacificIslander,EnglishOnly,Other,OtherIndo-European,Spanish,LanguageRWT
0,Advanced Practice Nursing,Clinical Nurse Specialist,Central Coast,31-45,1.050213,10.365144,0.000000,1.050213,6.301277,17.716634
1,Advanced Practice Nursing,Clinical Nurse Specialist,Central Coast,46-60,3.314445,29.504307,2.155347,0.996249,6.628890,41.602989
2,Advanced Practice Nursing,Clinical Nurse Specialist,Central Coast,61-75,0.989331,28.794373,0.000000,0.996249,0.989331,31.769284
3,Advanced Practice Nursing,Clinical Nurse Specialist,Central Coast,75 and Over,0.000000,0.989331,0.000000,0.000000,0.000000,0.989331
4,Advanced Practice Nursing,Clinical Nurse Specialist,Greater Bay Area,30 and Under,1.018601,3.055803,1.018601,1.018601,0.000000,5.093005
5,Advanced Practice Nursing,Clinical Nurse Specialist,Greater Bay Area,31-45,37.015108,149.178471,8.256200,9.278684,25.687764,225.280455
6,Advanced Practice Nursing,Clinical Nurse Specialist,Greater Bay Area,46-60,56.571683,239.290235,4.983497,23.805916,44.381550,355.141746
7,Advanced Practice Nursing,Clinical Nurse Specialist,Greater Bay Area,61-75,24.003945,117.318354,3.841503,6.738971,15.366011,165.337138
8,Advanced Practice Nursing,Clinical Nurse Specialist,Greater Bay Area,75 and Over,0.000000,10.624052,0.000000,0.965823,0.000000,11.589874
9,Advanced Practice Nursing,Clinical Nurse Specialist,Inland Empire,31-45,5.586810,21.541450,4.673581,1.880176,7.359548,40.128337

## **Dataset 5: Healthcare Workforce Language Spoken**

This dataset contains information about the languages spoken by healthcare professionals across different occupations, regions, and age groups. It shows the percentage of professionals who speak English, Spanish, Asian and Pacific Islander languages, Indo-European languages, and other languages.

**Features**


**WorkforceCategory**: The specific classification of healthcare profession

**LicenseName:** Name of the professional license associated with the healthcare occupation

**Region:** Geographic location where healthcare workforce data was collected

**AgeRange:** Lower and upper age limit in which the professionals were grouped

**AsianandPacificIslander:** Percentage of professionals who speak Asian and Pacific Islander languages

**EnglishOnly:** Percentage of professionals who speak speak only English

**Other:** Percentage of professionals who speak languages other than those specifically listed

**OtherIndo-European:** Percentage of professionals who speak other Indo-European languages

**Spanish:** Percentage of professionals who speak Spanish

**LanguageRWT:** A measurement value associated with the language data

In [12]:
df6 = pd.read_json("/content/Mydata/dataset.json")
df6.head(10)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC_DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL_CONSUMING,COUGHING,SHORTNESS_OF_BREATH,SWALLOWING_DIFFICULTY,CHEST_PAIN,LUNG_CANCER
0,M,65,1,1,1,2,2,1,2,2,2,2,2,2,1,NO
1,F,55,1,2,2,1,1,2,2,2,1,1,1,2,2,NO
2,F,78,2,2,1,1,1,2,1,2,1,1,2,1,1,YES
3,M,60,2,1,1,1,2,1,2,1,1,2,1,2,2,YES
4,F,80,1,1,2,1,1,2,1,2,1,1,1,1,2,NO
5,F,58,1,1,1,2,2,2,2,1,2,2,1,1,2,YES
6,F,70,1,1,1,2,2,1,2,2,2,2,2,2,1,YES
7,F,74,2,2,1,1,1,1,2,1,1,1,1,2,1,NO
8,M,77,1,2,1,2,1,1,1,1,2,1,1,1,2,NO
9,F,67,2,2,2,2,1,2,2,1,2,1,2,1,1,NO

## **Dataset 6: Lung Cancer**

This dataset contains demographic, lifestyle, and health related information about individuals that may be associated with lung cancer. it includes factors such as age, smoking, symptoms and other health conditions.

**Features**

**GENDER:**
Gender identity of individual

**AGE:**
Age of indiviudal

**SMOKING:**
Smoking status of individual

**YELLOW_FINGERS:**
Indicates whether the individual has yellow fingers a physical sign of long-term tobacco use

**ANXIETY:**
Indicates whether the individual experiences anxiety.  

**PEER_PRESSURE:**
Indicates if tobacco use formed as result of peer pressure

**CHRONIC_DISEASE:**
Indicates if individual has a chronic disease

**FATIGUE**
Indicates whether fatigue was reported, a symptom of various health conditions

**ALLERGY:**
Indicates whether the indivudal has allergies

**WHEEZING:**
Indicates whether indiviual has experienced wheezing, a symptom associated with various lung conditions  

**ALCOHOL_CONSUMING:**
Indicates alcohol consumption, a lifestyle factor

**COUGHING:**
Indicates whether the individual experiences coughing, a symptom associated with  various lung conditions  

**SHORTNESS_OF_BREATH:**
Indicates whether the individual experiences shortness of breath, a symptom associated with various lung conditions  

**SWALLOWING_DIFFICULTY:**
Indicates whether the individual experiences swallowing difficulty, a symptom associated with certain conditions  

**CHEST_PAIN:**
Indicates whether the individual experiences chest pain, a symptom associated with various lung conditions  

**LUNG_CANCER:**
indicates the recorded lung cancer outcome

In [13]:
df7 = pd.read_json("/content/Mydata/student_performance.json")
df7.head(10)

,Student_ID,Age,Gender,Parental_Education,Family_Support,Internet_Access,Extra_Curricular_Activities,Health_Status,Attendance_Percentage,Absences,Study_Hours,Previous_Grade,Final_Score,Pass_Fail
0,S0001,19,Male,Master,High,Yes,Yes,Good,82,11,9,77,80,Pass
1,S0002,19,Male,Bachelor,High,Yes,No,Poor,89,7,3,68,68,Pass
2,S0003,15,Male,PhD,Medium,No,Yes,Average,67,17,3,83,65,Pass
3,S0004,20,Male,HighSchool,High,No,No,Poor,57,22,6,73,63,Pass
4,S0005,20,Female,None,High,Yes,No,Poor,68,17,2,76,62,Pass
5,S0006,22,Male,Master,High,Yes,No,Poor,60,20,4,66,61,Pass
6,S0007,22,Male,Bachelor,Medium,No,Yes,Good,78,15,2,95,71,Pass
7,S0008,22,Male,Bachelor,Low,Yes,No,Poor,68,18,9,78,89,Pass
8,S0009,16,Female,None,High,No,Yes,Average,90,10,2,66,67,Pass
9,S0010,22,Male,Master,Medium,Yes,No,Average,62,22,4,51,55,Pass

## **Dataset 7: Student Performance**
This dataset contains information about students and what factors may influence their academic performance.It includes information about students' education, family support, attendance, study habits, health, previous grades, and final academic outcomes.

**Features**

**Student_ID:**
Identifier assigned to each student

**Age**
The age of the student, which can be used to examine performance across age groups

**Gender:**
The gender of the student which can be used to examine performance across gender

**Parental_Education**
The highest level of education completed by the student's parent

**Family_Support:**
The level of support the student receives from their parent which may impact academic performance

**Internet_Access:**
Indicates whether the student has access to the internet, which can affect access to academic resources

**Extra_Curricular_Activities:**
Indicates whether the student participates in activities outside of their coursework

**Health_Status:**
Describes the student's health status, which may affect their ability to attend school and perform academically

**Attendance_Percentage**
The percentage of school attendance for that student which could be used to examine the relationship between attendance and performance

**Absences**
Number of times student was absent, which could be used to examine the relationship between absence and performance

**Study_Hours**
Number of hours students studied course material

**Previous_Grade**
Students grade from previous academic period

**Final_Score**
The final score students received, representing their performance at the end of the course or period.  

**Pass_Fail**
Indicates whether the student passed or failed

In [15]:
df8 = pd.read_json("/content/Mydata/iris.json")
df8.head(10)

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa
5          5.4         3.9          1.7         0.4  setosa
6          4.6         3.4          1.4         0.3  setosa
7          5.0         3.4          1.5         0.2  setosa
8          4.4         2.9          1.4         0.2  setosa
9          4.9         3.1          1.5         0.1  setosa

## **Dataset 8: Iris Data**

This dataset contains measurements of different physical characteristics of iris flowers and identifies their species.

**Features**

**sepalLength:**
The length of the flower's sepal measured in centimeters

**sepalWidth:**
The width of the flower's sepal measured in centimeters

**petalLength:**
The length of the flower's petal measured in centimeters

**petalWidth:**
The width of the flower's petal measured in centimeters

**species:**
The species of iris flower represented by each observation